// SPDX-License-Identifier: Apache-2.0

/**
 * The bot pacer's pacing rule — #92.
 *
 * A bot pacer is **a synthetic rider ahead of you on the route, riding a chosen
 * w/kg, that will not wait for you.** This file is the half of it that decides
 * *how hard the bot is pedalling right now*: a target intensity, a fixed mass,
 * and a rule that varies the power with the gradient so the pace feels like a
 * rider rather than a metronome. `@onyourleft/physics` turns that power into a
 * speed; `pacer/gap.ts` says how far ahead it has got.
 *
 * ## ⚠️ Why this is a rule and not a recording — read before changing anything
 *
 * [ADR 0007](../../../../docs/adr/0007-patent-posture.md) D4 draws a line, and
 * this file is on the safe side of it **by construction**. Peloton's
 * US 10,486,026 claim 1 needs *"archived performance data … previously
 * generated by the other users"*; US 11,170,886 claim 19 needs *"live
 * performance parameters"* collected from users' sensors during a live session.
 * A bot has neither, because **there is no recorded ride behind it, from this
 * rider or from anyone else**. Its whole input is:
 *
 * | Input | What it is |
 * |---|---|
 * | {@link BotPacerPlan.intensityWattsPerKilogram} | a number the rider chose on a screen before starting |
 * | {@link BotPacerPlan.massKilograms} | {@link BOT_MASS_KILOGRAMS}, a constant |
 * | `RouteProfile` | elevation as a function of **distance**, built from a GPX file (#89). It has no time axis, no power, no heart rate and no athlete: there is nowhere in it for a performance to be |
 * | elapsed time | a `Seconds` the caller supplies, the same way the recording engine takes one |
 *
 * That table is the review criterion #92 asks for, and it is **checked rather
 * than asserted** in three places, which is the standard CLAUDE.md §5 sets:
 *
 * 1. {@link BotPacerPlan} is constrained at compile time to hold nothing but
 *    scalars — see `SyntheticInput` below. A field typed as a sample series, an
 *    activity id or an athlete id makes this file fail to typecheck.
 * 2. `pacing.test.ts` walks the actual objects a bot is handed at runtime and
 *    fails on any key outside a named allowlist.
 * 3. `packages/domain` may name **no platform API at all**, so there is no I/O
 *    through which stored data could arrive other than these parameters. That
 *    gate is `tsconfig.json` and `eslint.config.js`, and it already exists.
 *
 * There is no ranking here, and no comparison against any other person: the
 * only comparison this feature makes is the rider against the bot, and the bot
 * is arithmetic. `pacer.test.ts` asserts the exported surface of both files
 * names no athlete, activity, effort, ghost or leaderboard.
 *
 * ## Nothing here reads a clock
 *
 * The rule that binds the recording engine and #90's setpoint driver binds
 * this: **time arrives as a parameter.** A bot that moved between two runs of
 * the same test would not be testable, and #92's whole claim — that the bot is
 * computed rather than replayed — rests on the output being a function of the
 * inputs above and nothing else.
 */

import type { GradePercent, Kilograms, Watts } from '../quantities';
import { kilograms, watts } from '../quantities';
import { PacerError } from './errors';

/**
 * The bot's mass, rider and bicycle together: **75 kg**, regardless of the
 * rider's own.
 *
 * This is the documented mechanic #92 names, and the reason for it is that the
 * advertised number has to mean the same thing to everybody. A pacer
 * advertising "2.5 w/kg" that weighed what *you* weigh would ride at a
 * different speed for every rider, so two riders comparing notes about the same
 * pacer would be describing different rides — and a lighter rider would find
 * the same advertised bot slower, which is the opposite of the intuition the
 * number creates.
 *
 * ⚠️ It is deliberately **not** the rider's mass and must not be replaced by
 * it. The rider's own mass belongs to the rider's own physics; the bot's is a
 * constant so that the advertised intensity is a promise about the bot's speed.
 */
export const BOT_MASS_KILOGRAMS = 75;

/**
 * The most the bot lifts its power above the flat figure, climbing: **+10 %**.
 *
 * The uphill half of the envelope #92 states. It is small on purpose: a real
 * rider holding a steady effort does push a little harder up a rise, but not
 * much — the gradient does most of the work of slowing them down, and a pacer
 * that surged 40 % on every ramp would be a rider you cannot sit behind.
 */
export const PACING_MAXIMUM_UPLIFT = 0.1;

/**
 * The most the bot drops its power below the flat figure, descending:
 * **−20 %**.
 *
 * The downhill half, and twice the uphill one, which is not an accident: on a
 * descent gravity is already supplying the speed, so power spent there buys
 * very little, and a real rider eases off or stops pedalling entirely. The
 * asymmetry is what makes the bot's pace feel ridden rather than computed.
 */
export const PACING_MAXIMUM_EASING = 0.2;

/**
 * The gradient at which the bot is pushing as hard as it ever will: **8 %**.
 *
 * Below it the uplift ramps in proportion; at and above it the bot is at
 * {@link PACING_MAXIMUM_UPLIFT} and pushes no harder however steep the road
 * gets. 8 % is about where a climb stops being a rise and starts being a climb.
 *
 * ⚠️ **This is a feel parameter, not a measured constant**, and it is flagged
 * the way `packages/physics` flags its two weakest numbers. Nothing in a
 * published paper says a rider's power rises linearly to a ceiling at 8 %.
 * What is published is the *envelope* (#92's +10 %/−20 %); the shape inside it
 * is this project's, chosen to be the simplest thing that satisfies the
 * envelope, is monotonic in gradient, and is continuous at zero. Tune it.
 */
export const PACING_CLIMB_REFERENCE_GRADE_PERCENT = 8;

/**
 * The gradient at which the bot has eased off as far as it ever will: **−6 %**,
 * expressed here as a positive magnitude.
 *
 * Shorter than the climbing reference above, so the bot eases *earlier* than it
 * pushes — a rider soft-pedals as soon as the road tips down, well before they
 * would be out of the saddle on the equivalent climb. Same flag as
 * {@link PACING_CLIMB_REFERENCE_GRADE_PERCENT}: a feel parameter, chosen and
 * not measured.
 */
export const PACING_DESCENT_REFERENCE_GRADE_PERCENT = 6;

/**
 * The top of the envelope, as a multiplier of the flat power. Derived, so a
 * test asserting the envelope and the rule producing it cannot drift apart.
 */
export const PACING_FACTOR_CEILING = 1 + PACING_MAXIMUM_UPLIFT;

/** The bottom of the envelope, as a multiplier of the flat power. Derived. */
export const PACING_FACTOR_FLOOR = 1 - PACING_MAXIMUM_EASING;

/**
 * The gentlest pace a bot will ride: **0.5 w/kg**, or about 38 W at
 * {@link BOT_MASS_KILOGRAMS}.
 *
 * A bound on a rider's choice rather than on the model. Below this the bot is
 * not pacing anything — 38 W on the flat is walking speed on a bicycle — and a
 * "pacer" that a rider passes at a standstill is a bug report rather than a
 * feature.
 */
export const MINIMUM_INTENSITY_WATTS_PER_KILOGRAM = 0.5;

/**
 * The hardest pace a bot will ride: **7 w/kg**, or 525 W at
 * {@link BOT_MASS_KILOGRAMS}.
 *
 * Comfortably above any human hour record and therefore above anything worth
 * chasing for the length of a route. The bound exists because the intensity
 * arrives from a control on a screen, and a slipped decimal point should be
 * refused with a message rather than ridden away from.
 */
export const MAXIMUM_INTENSITY_WATTS_PER_KILOGRAM = 7;

/**
 * What the bot is trying to do: an intensity, and the mass it is applied to.
 *
 * **Both fields are scalars, and that is enforced rather than intended** — see
 * `SyntheticInput` below and the header. Build one with {@link botPacerPlan},
 * which is where the bounds above are applied.
 */
export interface BotPacerPlan {
  /**
   * The advertised pace, in watts per kilogram.
   *
   * A plain number rather than a branded quantity, for the reason
   * `packages/physics` gives about its coefficients: `packages/domain` has no
   * type for a specific power and #92 is not the issue that adds one. The unit
   * is in the field name, which is this package's fallback where a brand does
   * not exist.
   */
  readonly intensityWattsPerKilogram: number;
  /** Always {@link BOT_MASS_KILOGRAMS} unless a test or a tuner says otherwise. */
  readonly massKilograms: Kilograms;
}

/**
 * A compile-time constraint that a bot's inputs can hold **nothing but
 * scalars**.
 *
 * Every field of `T` that is not a number, a boolean or a string maps to
 * `never`, so a type constrained by this stops satisfying its own constraint
 * the moment somebody adds a field that could carry a recorded ride: a sample
 * series, a stream, an effort, an activity id (an object or an array) — and,
 * for anything sneakier, a nested object of any shape at all.
 *
 * ⚠️ **A branded quantity is a number and passes**, which is correct: `Watts`,
 * `Seconds` and `Kilograms` are single readings, not recordings. What cannot
 * pass is a *collection* of them against a timeline, which is what every
 * recorded ride in this program is (`RecordedSeries`, `PowerSeries`,
 * `SegmentEffort`, `SignedActivityRecord` — all objects or arrays).
 *
 * This is not the whole proof and does not pretend to be; the header lists all
 * three parts and this is the one a typechecker can carry.
 */
type SyntheticInput<T> = {
  readonly [K in keyof T]: T[K] extends number | boolean | string ? T[K] : never;
};

/**
 * Applies {@link SyntheticInput} as a **constraint**, which is what makes it an
 * error rather than a silent `never`.
 *
 * ⚠️ The direction matters and the other one is a trap. Writing the check as
 * `SyntheticInput<T> extends T ? … : never` looks equivalent and enforces
 * nothing: the mapped type turns a rejected field into `never`, and `never` is
 * assignable to *everything*, so that conditional stays true however bad `T`
 * gets. It has to be `T extends SyntheticInput<T>` — the offending field is
 * then a `number[]` being checked against `never`, which fails — and it has to
 * be a constraint on a type parameter, because a conditional type that
 * evaluates to `never` is a perfectly legal type and nothing reports it.
 */
type AssertSynthetic<T extends SyntheticInput<T>> = T;

/**
 * The assertion itself: this alias fails to compile with `TS2344` if
 * {@link BotPacerPlan} ever gains a field {@link SyntheticInput} rejects.
 *
 * Exported so that it is *used* — an unused local type alias is a lint error,
 * and a guarantee deleted by a linter is worse than no guarantee. `pacing.test.ts`
 * names it as the thing that would have failed, and holds the `@ts-expect-error`
 * cases that make its absence visible (CLAUDE.md §5, "Verifying a compile-time
 * guarantee").
 */
export type BotPacerPlanIsSynthetic = AssertSynthetic<BotPacerPlan>;

/**
 * Build a plan, applying the bounds a rider's choice has to be inside.
 *
 * @param intensityWattsPerKilogram - the advertised pace, between
 * {@link MINIMUM_INTENSITY_WATTS_PER_KILOGRAM} and
 * {@link MAXIMUM_INTENSITY_WATTS_PER_KILOGRAM}.
 * @param massKilograms - defaults to {@link BOT_MASS_KILOGRAMS}. A tunable for
 * tests and for whoever decides one day that 75 kg was the wrong constant; not
 * a place to put the rider's mass.
 * @throws {PacerError} `intensity-out-of-range` or `mass-out-of-range`, both
 * naming the constraint they failed.
 */
export function botPacerPlan(
  intensityWattsPerKilogram: number,
  massKilograms: number = BOT_MASS_KILOGRAMS,
): BotPacerPlan {
  if (
    !Number.isFinite(intensityWattsPerKilogram) ||
    intensityWattsPerKilogram < MINIMUM_INTENSITY_WATTS_PER_KILOGRAM ||
    intensityWattsPerKilogram > MAXIMUM_INTENSITY_WATTS_PER_KILOGRAM
  ) {
    throw new PacerError(
      'intensity-out-of-range',
      `a pacer's target intensity must be between ` +
        `${String(MINIMUM_INTENSITY_WATTS_PER_KILOGRAM)} and ` +
        `${String(MAXIMUM_INTENSITY_WATTS_PER_KILOGRAM)} watts per kilogram, received ` +
        `${String(intensityWattsPerKilogram)}`,
    );
  }
  if (!Number.isFinite(massKilograms) || massKilograms <= 0) {
    throw new PacerError(
      'mass-out-of-range',
      `a pacer's mass must be a finite mass greater than zero kilograms, received ` +
        `${String(massKilograms)}`,
    );
  }
  return {
    intensityWattsPerKilogram,
    massKilograms: kilograms(massKilograms),
  };
}

/**
 * What the bot rides on the flat: the advertised intensity times the mass.
 *
 * The reference every other power in this file is a fraction of, which is why
 * it is exported: a test asserting the envelope has to be able to say what the
 * envelope is around, and re-deriving it at the call site is how the two stop
 * agreeing.
 */
export function flatPowerWatts(plan: BotPacerPlan): Watts {
  return watts(plan.intensityWattsPerKilogram * plan.massKilograms);
}

/**
 * The multiplier the gradient applies to {@link flatPowerWatts}.
 *
 * Ramps linearly to {@link PACING_FACTOR_CEILING} at
 * {@link PACING_CLIMB_REFERENCE_GRADE_PERCENT} and to
 * {@link PACING_FACTOR_FLOOR} at minus
 * {@link PACING_DESCENT_REFERENCE_GRADE_PERCENT}, and saturates beyond each.
 * Continuous at zero, where it is exactly 1, and monotonically increasing in
 * the gradient — both are asserted in `pacing.test.ts`, because a rule that
 * dipped anywhere would have the bot easing off on a steeper climb.
 *
 * A non-finite gradient returns 1 rather than throwing, the way #90's driver
 * treats one: the profile is a route file's, the caller is mid-ride, and the
 * safe answer is the flat pace rather than a stopped bot.
 */
export function pacingFactor(grade: GradePercent | number): number {
  // Widened to a plain number before any arithmetic: `GradePercent` is a
  // branded type, and negating one is a lint error rather than a unit-safe
  // operation (`@typescript-eslint/no-unsafe-unary-minus`). The brand has done
  // its job at the parameter.
  const value: number = grade;
  if (!Number.isFinite(value)) return 1;
  if (value >= 0) {
    const response = Math.min(value / PACING_CLIMB_REFERENCE_GRADE_PERCENT, 1);
    return 1 + response * PACING_MAXIMUM_UPLIFT;
  }
  const response = Math.min(-value / PACING_DESCENT_REFERENCE_GRADE_PERCENT, 1);
  return 1 - response * PACING_MAXIMUM_EASING;
}

/**
 * What the bot is pedalling at this gradient: the whole pacing rule.
 *
 * `@onyourleft/physics` calls this once per tick and hands the result to the
 * same `advance` the rider's own ride goes through. Nothing between here and
 * there reads anything that is not in {@link BotPacerPlan} or the route.
 */
export function pacedPowerWatts(plan: BotPacerPlan, grade: GradePercent | number): Watts {
  return watts(flatPowerWatts(plan) * pacingFactor(grade));
}
