// SPDX-License-Identifier: AGPL-3.0-or-later

import { useMemo, type JSX } from 'react';

import { creditsFrom, externalLink, licenceLink, type CreditedWork } from '../credits/credits';
import { parseAssetManifest } from '../credits/manifest';
import { parseNotices, THIRD_PARTY_NOTICES_URL, type IncludedSoftware } from '../credits/notices';
import { THIRD_PARTY_CONTENTS_SOURCE } from '../credits/notices-source';
import { ASSET_MANIFEST_SOURCE } from '../credits/source';
import { StatusMessage } from '../design/StatusMessage';

/**
 * Who made the art this app ships, generated from `ASSETS.toml` — #358.
 *
 * ## Why this page exists, and why it is not a list somebody maintains
 *
 * [ADR 0023](../../../../docs/adr/0023-cc-by-assets-and-attribution.md) admits `CC-BY-4.0`
 * for a committed asset, and CC BY is the one licence in this repository whose
 * obligation never ends: it is discharged by the shipped application crediting
 * the work, every time it ships. §3(a)(2) lets that be satisfied *"in any
 * reasonable manner based on the medium"*, and the medium here is an APK —
 * somebody who installs this app never sees the repository, so a row in a file
 * in git is not reasonably discoverable *by them*. This screen is where the
 * notice is discoverable, beside the AGPL statement on the About page that is
 * there for the same reason.
 *
 * ⚠️ **It is derived, not written.** `ASSET001` already forces `ASSETS.toml` to
 * name every committed binary — a binary it does not name is a red build, and
 * discovery walks the tree rather than trusting an extension list. A screen
 * generated from the manifest inherits that completeness; a hand-maintained
 * list cannot, and ADR 0023 §"What would make this ADR wrong" says a
 * hand-maintained credits list should be read as the failure of that decision
 * rather than as a workaround.
 *
 * ## The sections, and the one that must not imply an obligation
 *
 * The first section is what the app **must** credit. The second — since
 * #597 — is work whose licence asks for no credit but does ask for a copy of
 * the licence to travel with it (Apache-2.0: the map's Roboto glyphs and the
 * pose model), and each links the copy this app ships. The third is offered
 * anyway, for assets whose licence asks for nothing. They are separate, and
 * the courtesy one says in words that nothing is owed, because #358's third
 * bullet is that the screen *"must not imply an obligation that does not
 * exist"* — and ⚠️ until #597 the courtesy sentence was said of the two
 * Apache-2.0 works too, which is the converse mistake: denying one that does.
 *
 * ## What is rendered when something is wrong
 *
 * A manifest line the client cannot read, and an attribution-requiring entry
 * with a key missing, are both **shown**. `ASSET006` and `ASSET005` already
 * make each a red build, so neither can reach a release — and the answer to
 * "what if one does" is a visible problem rather than a row quietly missing
 * from the page. A dropped row is an asset credited nowhere, which is the one
 * outcome ADR 0023 §Consequences calls a licensing defect.
 *
 * ## The software, since #664
 *
 * The art is not the only thing here somebody else made. The app ships forty
 * packages of other people's code and the APK fifty native libraries more,
 * each under a licence that asks for its notice to travel with copies, and
 * until #664 none did. The last section lists every one, generated by
 * `scripts/check-third-party-notices.mjs` from the installed tree, and links
 * the document that reproduces every notice in full — served from this app's
 * own files, so it opens offline and inside the APK. ⚠️ An empty list is
 * rendered as a problem rather than as nothing: the same reason as the
 * attribution section's fixture, applied to a list that cannot legitimately be
 * empty.
 */

export interface CreditsViewProps {
  /**
   * The manifest to credit from. Defaults to the one built into this bundle.
   *
   * A prop only so that `CreditsView.test.tsx` can render a manifest carrying
   * a `CC-BY-4.0` asset. There is none in the tree — ADR 0023 D-7 makes this
   * screen the thing that lands before the first one — so without it every
   * assertion about the attributed half would pass over an empty list.
   */
  readonly manifest?: string;
  /**
   * The third-party notices' contents. Defaults to the ones built into this
   * bundle; a prop so `CreditsView.test.tsx` can render a fixture and prove
   * a named package reaches the screen, and a broken document says so.
   */
  readonly notices?: string;
}

/**
 * The sentence CC BY 4.0 §3(a)(1)(A)(ii) and (iii) ask for, once.
 *
 * ADR 0023 D-3: the copyright notice and the warranty disclaimer are the same
 * sentence for every attributed work, so they are the screen's own wording
 * rather than a per-asset key that could drift row by row.
 */
const NOTICE =
  'Each work below remains the copyright of its creator and is used under the licence named ' +
  'beside it. The material is provided as-is, without warranties of any kind.';

/** One work, its licence, what was changed, and the files taken from it. */
function Work({ work }: { readonly work: CreditedWork }): JSX.Element {
  const licence = licenceLink(work.licence);
  const original = externalLink(work.url);
  return (
    <li>
      <p>
        <strong>{work.creator === '' ? 'Creator not recorded' : work.creator}</strong>
        {original === undefined ? null : (
          <>
            {' — '}
            <a href={original} target="_blank" rel="noreferrer">
              the original
            </a>
          </>
        )}
        {', under '}
        {licence === undefined ? (
          work.licence
        ) : (
          <a href={licence} target="_blank" rel="noreferrer">
            {work.licence}
          </a>
        )}
        .
      </p>
      <p>{modificationNote(work)}</p>
      <ul>
        {work.files.map((file) => (
          <li key={file}>
            <code>{file}</code>
          </li>
        ))}
      </ul>
    </li>
  );
}

/** A list of works, keyed by the first file each one took. */
function WorkList({ works }: { readonly works: readonly CreditedWork[] }): JSX.Element {
  return (
    <ul>
      {works.map((work) => (
        <Work key={`${work.creator}${work.licence}${work.files[0] ?? ''}`} work={work} />
      ))}
    </ul>
  );
}

/**
 * What the modification note says.
 *
 * ⚠️ `"no"` is a recorded answer rather than an absent one — ADR 0023 D-3 —
 * so it is rendered as a statement rather than as silence. A work whose entry
 * records nothing at all says that too, because the alternative is the screen
 * claiming an asset is unmodified on no evidence.
 */
function modificationNote(work: CreditedWork): string {
  if (work.modified === undefined) {
    return 'Whether this app changed it is not recorded.';
  }
  return work.modified.trim().toLowerCase() === 'no'
    ? 'Used unmodified.'
    : `Modified by this app: ${work.modified}`;
}

/** One package, its version and the licence it declares. */
function SoftwareList({ items }: { readonly items: readonly IncludedSoftware[] }): JSX.Element {
  return (
    <ul>
      {items.map((item) => (
        <li key={`${item.name}@${item.version}`}>
          <code>{item.name}</code> {item.version}, under {item.licence}
        </li>
      ))}
    </ul>
  );
}

export function CreditsView({ manifest, notices }: CreditsViewProps): JSX.Element {
  const credits = useMemo(
    () => creditsFrom(parseAssetManifest(manifest ?? ASSET_MANIFEST_SOURCE)),
    [manifest],
  );
  const software = useMemo(() => parseNotices(notices ?? THIRD_PARTY_CONTENTS_SOURCE), [notices]);

  return (
    <>
      {credits.problems.length === 0 ? null : (
        <StatusMessage tone="warning" label="This page may be incomplete">
          <p>
            Some of what this app records about its assets could not be read, so somebody may be
            missing from this page.
          </p>
          <ul>
            {credits.problems.map((problem) => (
              <li key={problem}>{problem}</li>
            ))}
          </ul>
        </StatusMessage>
      )}

      <p>
        This page is generated from the record this app keeps of every file it ships that somebody
        else made — the artwork in the trainer game, the lettering on the map, the side
        camera&rsquo;s pose model, and the templates the Android build is assembled from. Nothing
        here is typed by hand, so an asset cannot be added without appearing here. The last section
        does the same for the software the app is built from. Links to the originals open in a new
        tab.
      </p>

      <div data-terms="attribution">
        <h2>Credited because the licence asks for it</h2>
        {credits.required.length === 0 ? (
          <StatusMessage tone="info" label="Nothing owed">
            No asset in this build is under a licence that requires attribution. Nothing below is
            credited because a licence asks for a credit; where a licence asks for something else,
            that is said beside it.
          </StatusMessage>
        ) : (
          <>
            <p>{NOTICE}</p>
            <WorkList works={credits.required} />
          </>
        )}
      </div>

      {credits.licenceCopy.length === 0 ? null : (
        <div data-terms="licence-copy">
          <h2>Shipped with a copy of its licence</h2>
          <p>
            Each of these is published under a licence that does not ask to be credited on a screen,
            but does ask that a copy of the licence travel with the work. That copy ships inside
            this app, and the licence named beside each work opens it.
          </p>
          <WorkList works={credits.licenceCopy} />
        </div>
      )}

      <div data-terms="nothing">
        <h2>Credited as a courtesy</h2>
        {credits.courtesy.length === 0 ? (
          <p>
            {credits.licenceCopy.length === 0 && credits.unclassified.length === 0
              ? 'Nothing else in this build came from somebody outside this project.'
              : 'Nothing in this build is under a licence that asks for nothing at all.'}
          </p>
        ) : (
          <>
            <p>
              Each of these is published under a licence that asks for nothing in return — no credit
              is required and none is implied to be owed. They are here because the work was worth
              crediting anyway.
            </p>
            <WorkList works={credits.courtesy} />
          </>
        )}
      </div>

      {credits.unclassified.length === 0 ? null : (
        <div data-terms="unclassified">
          <h2>Credited under another licence</h2>
          <p>
            This page has not been told what these licences ask for, so it says nothing about it.
            The licence named beside each work is the one that applies.
          </p>
          <WorkList works={credits.unclassified} />
        </div>
      )}

      <h2>Where this list comes from</h2>
      <p>
        From <code>ASSETS.toml</code> in this project&rsquo;s own repository, which records the
        source, the licence and a checksum for every file of somebody else&rsquo;s that is committed
        to it. A file that is not recorded there fails the build, so this page is as complete as
        that record is.
      </p>

      <div data-terms="software">
        <h2>Software this app includes</h2>
        <p>
          This app is built from open-source software written by other people, and each part is used
          under the licence named beside it. Every one of those licences asks for its notice to
          travel with the software, and{' '}
          <a href={THIRD_PARTY_NOTICES_URL} target="_blank" rel="noreferrer">
            the full third-party notices
          </a>{' '}
          reproduce each one word for word. That document ships inside this app, so it opens without
          a network.
        </p>
        {software.app.length === 0 || software.problems.length > 0 ? (
          <StatusMessage tone="warning" label="This list may be incomplete">
            <p>
              The list of software this app includes could not be read in full, so a package may be
              missing below. The full notices are still the document linked above.
            </p>
            {software.problems.length === 0 ? null : (
              <ul>
                {software.problems.map((problem) => (
                  <li key={problem}>{problem}</li>
                ))}
              </ul>
            )}
          </StatusMessage>
        ) : null}
        <h3>In the app</h3>
        <p>
          What a browser downloads when it opens this app. The Android app carries all of it too.
        </p>
        <SoftwareList items={software.app} />
        <h3>In the Android app only</h3>
        <p>
          The native libraries the Android app is built with, beside the app above. A browser never
          downloads these.
        </p>
        <SoftwareList items={software.android} />
        <p>
          Generated from this project&rsquo;s installed dependencies rather than typed by hand, and
          checked on every change: a package added without its notice fails the build.
        </p>
      </div>
    </>
  );
}
