#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Tests for scripts/check-capacitor-generated.mjs.
#
# Same shape as the other suites: each case builds a throwaway Capacitor
# project, runs the checker against it, and asserts on the output and the exit
# code.
#
# ⚠️ **Two of the red cases are the drift that actually happened**, reproduced
# from the tree as it was, because a gate that cannot reproduce what motivated
# it is the thing #299 exists to prevent:
#
#   git show 2008cfa^:apps/mobile/android/capacitor.settings.gradle  # the
#     8.5.1/8.5.1 path #276 and #277 left behind, fixed in #298
#   git show 6eda5e3^:apps/mobile/android/capacitor.settings.gradle  # #298's
#     own artefact, 8.5.1 android beside 8.5.2 core, fixed in #300
#
# The second is the more interesting one and has its own case: the `core` half
# is right and the `android` half is wrong, so a check that compares only one
# dependency, or stops at the first path in the file, passes it. That is the
# "first match and stop" shape #229 and #286 both took.
#
# The generator is substituted the way the real one is found -- the checker
# runs `apps/mobile/node_modules/.bin/cap`, and a fixture writes its own there.
# There is no test-only flag for it, so nothing here can be true of the fixture
# and false of the repository.
#
# Unlike the four bare-clone checkers this one needs Node and pnpm, so it is NOT
# part of `pnpm run check:repo`.
#
# Run: bash scripts/check-capacitor-generated.test.sh

# The assertions hold literal Markdown-ish text with backticks that must reach
# `grep -F` unexpanded, so they are single-quoted and SC2016 is the intended
# shape. Same call as scripts/check-wiring.test.sh makes.
# shellcheck disable=SC2016

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="${SCRIPT_DIR}/check-capacitor-generated.mjs"

pass=0
fail=0
tmp=""

cleanup() { [ -n "${tmp}" ] && rm -rf "${tmp}"; }
trap cleanup EXIT

SETTINGS='apps/mobile/android/capacitor.settings.gradle'
BUILD='apps/mobile/android/app/capacitor.build.gradle'

# The committed file as it is on `main` today, trimmed to the two includes.
settings_at() {
  cat <<GRADLE
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../../../node_modules/.pnpm/@capacitor+android@$1/node_modules/@capacitor/android/capacitor')

include ':capacitor-community-bluetooth-le'
project(':capacitor-community-bluetooth-le').projectDir = new File('../../../node_modules/.pnpm/@capacitor-community+bluetooth-le@8.3.0_@capacitor+core@$2/node_modules/@capacitor-community/bluetooth-le/android')
GRADLE
}

build_with() {
  cat <<GRADLE
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
dependencies {
    implementation project(':$1')
}
GRADLE
}

# new_fixture -- a project with both generated files committed at the versions
# given, and no generator yet.
#
#   new_fixture <settings android+core suffix> <bluetooth core suffix>
new_fixture() {
  tmp="$(mktemp -d)"
  mkdir -p "${tmp}/apps/mobile/android/app" "${tmp}/apps/mobile/node_modules/.bin"
  settings_at "${1:-8.5.2_@capacitor+core@8.5.2}" "${2:-8.5.2}" > "${tmp}/${SETTINGS}"
  build_with capacitor-community-bluetooth-le > "${tmp}/${BUILD}"
}

# fake_cap -- the generator's body on stdin. It runs with cwd = apps/mobile.
fake_cap() {
  {
    printf '#!/usr/bin/env bash\nset -euo pipefail\n'
    cat
  } > "${tmp}/apps/mobile/node_modules/.bin/cap"
  chmod +x "${tmp}/apps/mobile/node_modules/.bin/cap"
}

# generator_writing -- the common case: a generator that writes the two files at
# the versions given.
generator_writing() {
  local android="$1" core="$2" plugin="${3:-capacitor-community-bluetooth-le}"
  fake_cap <<SH
$(declare -f settings_at)
$(declare -f build_with)
settings_at '${android}' '${core}' > android/capacitor.settings.gradle
build_with '${plugin}' > android/app/capacitor.build.gradle
SH
}

# run_check -- output on stdout+stderr, exit code in ${code}.
run_check() {
  out="$(node "${CHECK}" --root "${tmp}" --assume-installed 2>&1)"
  code=$?
}

# run_check_installing -- the production invocation, with no --assume-installed.
run_check_installing() {
  out="$(node "${CHECK}" --root "${tmp}" 2>&1)"
  code=$?
}

assert_green() {
  local name="$1"
  if [ "${code}" -eq 0 ]; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL: %s\n  expected exit 0, got %d:\n%s\n\n' "${name}" "${code}" "${out}"
  fi
}

assert_red() {
  local name="$1"
  if [ "${code}" -ne 0 ]; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL: %s\n  expected a non-zero exit, got 0:\n%s\n\n' "${name}" "${out}"
  fi
}

assert_says() {
  local name="$1" expected="$2"
  if printf '%s' "${out}" | grep -qF -- "${expected}"; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL: %s\n  expected to contain: %s\n  got:\n%s\n\n' "${name}" "${expected}" "${out}"
  fi
}

assert_silent_about() {
  local name="$1" unexpected="$2"
  if printf '%s' "${out}" | grep -qF -- "${unexpected}"; then
    fail=$((fail + 1))
    printf 'FAIL: %s\n  expected NOT to mention: %s\n  got:\n%s\n\n' "${name}" "${unexpected}" "${out}"
  else
    pass=$((pass + 1))
  fi
}

# assert_file_is -- the file at ${tmp}/$2 holds exactly what stdin says.
assert_file_is() {
  local name="$1" path="$2" expected
  expected="$(cat)"
  if [ "$(cat "${tmp}/${path}")" = "${expected}" ]; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    printf 'FAIL: %s\n  %s is not what it was:\n%s\n\n' "${name}" "${path}" "$(cat "${tmp}/${path}")"
  fi
}

# --- The agreeing case -------------------------------------------------------
new_fixture
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2'
run_check
assert_green 'a file the generator reproduces byte for byte passes'
assert_says 'and names both files it compared' 'apps/mobile/android/app/capacitor.build.gradle'
assert_says 'and says it regenerated rather than merely looked' 'regenerated and byte-identical'

# --- The marker does not survive a green run ---------------------------------
# ⚠️ The check overwrites each file before running the generator. A green run
# that left the marker behind would be a check that had corrupted the tree.
assert_silent_about 'a green run leaves no marker in its own output' 'killed mid-run'
if grep -q 'check-capacitor-generated' "${tmp}/${SETTINGS}"; then
  fail=$((fail + 1))
  printf 'FAIL: a green run left its marker in the committed file\n\n'
else
  pass=$((pass + 1))
fi

# --- #276/#277: the bump that left 8.5.1 behind ------------------------------
new_fixture '8.5.1_@capacitor+core@8.5.1' '8.5.1'
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2'
run_check
assert_red 'the 8.5.1 -> 8.5.2 drift fails'
assert_says 'and names the rule and the file' 'CAP004 apps/mobile/android/capacitor.settings.gradle'
assert_says 'and quotes the path that is no longer there' '@capacitor+android@8.5.1_@capacitor+core@8.5.1'
assert_says 'and quotes the path that is' '@capacitor+android@8.5.2_@capacitor+core@8.5.2'
assert_says 'and says which line' 'line 3:'
assert_says 'and says how to repair it, install first' 'pnpm install --frozen-lockfile && pnpm'

# --- The originals are put back ----------------------------------------------
# A checker that leaves the repaired file behind turns a red gate into a silent
# commit: `git add -A` would sweep it up and nobody would read the report.
assert_file_is 'a red run restores the committed bytes' "${SETTINGS}" <<'GRADLE'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../../../node_modules/.pnpm/@capacitor+android@8.5.1_@capacitor+core@8.5.1/node_modules/@capacitor/android/capacitor')

include ':capacitor-community-bluetooth-le'
project(':capacitor-community-bluetooth-le').projectDir = new File('../../../node_modules/.pnpm/@capacitor-community+bluetooth-le@8.3.0_@capacitor+core@8.5.1/node_modules/@capacitor-community/bluetooth-le/android')
GRADLE

# --- #298's own artefact: the core half right, the android half wrong --------
# ⚠️ The case that catches a check comparing one dependency, or stopping at the
# first path in the file. Line 3 is wrong; line 6 is right.
new_fixture '8.5.1_@capacitor+core@8.5.2' '8.5.2'
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2'
run_check
assert_red 'a file where only one of two paths is stale still fails'
assert_says 'and names the file' 'CAP004 apps/mobile/android/capacitor.settings.gradle'
assert_says 'and quotes the half that is wrong' '@capacitor+android@8.5.1_@capacitor+core@8.5.2'
assert_says 'and reports it at line 3' 'line 3:'
assert_silent_about 'and does not report the half that is right' 'line 6:'

# --- Drift in the second file alone ------------------------------------------
# The "checks only the first file" shape. capacitor.settings.gradle agrees.
new_fixture
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2' 'capacitor-community-bluetooth-le-2'
run_check
assert_red 'drift in the second file alone fails'
assert_says 'and names that file' 'CAP004 apps/mobile/android/app/capacitor.build.gradle'
assert_silent_about 'and does not accuse the file that agrees' 'CAP004 apps/mobile/android/capacitor.settings.gradle'

# --- Both files drift, and both are reported ---------------------------------
new_fixture '8.5.1_@capacitor+core@8.5.1' '8.5.1'
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2' 'capacitor-community-bluetooth-le-2'
run_check
assert_red 'both files drifting fails'
assert_says 'and the first is reported' 'CAP004 apps/mobile/android/capacitor.settings.gradle'
assert_says 'and so is the second' 'CAP004 apps/mobile/android/app/capacitor.build.gradle'

# --- CAP003: a generator that exits 0 and writes nothing ---------------------
# ⚠️ The anti-vacuity case. Without the marker this is a comparison of a file
# with itself, which passes whatever the file says -- #299's whole subject.
new_fixture
fake_cap <<'SH'
exit 0
SH
run_check
assert_red 'a generator that writes nothing is reported, not read as agreement'
assert_says 'and names the rule and the file' 'CAP003 apps/mobile/android/capacitor.settings.gradle'
assert_says 'and says why that is not a pass' 'comparing it proves nothing'
assert_silent_about 'and does not claim drift it did not measure' 'CAP004'

# --- ...and the tree is still what it was ------------------------------------
assert_file_is 'the marker is removed even when the generator ignored it' "${SETTINGS}" <<'GRADLE'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../../../node_modules/.pnpm/@capacitor+android@8.5.2_@capacitor+core@8.5.2/node_modules/@capacitor/android/capacitor')

include ':capacitor-community-bluetooth-le'
project(':capacitor-community-bluetooth-le').projectDir = new File('../../../node_modules/.pnpm/@capacitor-community+bluetooth-le@8.3.0_@capacitor+core@8.5.2/node_modules/@capacitor-community/bluetooth-le/android')
GRADLE

# --- CAP003: a generator that writes one file and not the other --------------
new_fixture
fake_cap <<SH
$(declare -f settings_at)
settings_at '8.5.2_@capacitor+core@8.5.2' '8.5.2' > android/capacitor.settings.gradle
SH
run_check
assert_red 'a generator that writes only one of the two is reported'
assert_says 'and names the one it skipped' 'CAP003 apps/mobile/android/app/capacitor.build.gradle'
assert_silent_about 'and not the one it wrote' 'CAP003 apps/mobile/android/capacitor.settings.gradle'

# --- CAP003: a generator that fails ------------------------------------------
new_fixture
fake_cap <<'SH'
echo 'could not find the android platform' >&2
exit 3
SH
run_check
assert_red 'a generator that exits non-zero fails the check'
assert_says 'and names the rule' 'CAP003 apps/mobile'
assert_says 'and quotes what it said' 'could not find the android platform'

# --- CAP003: no Capacitor CLI at all -----------------------------------------
new_fixture
run_check
assert_red 'a tree with no Capacitor CLI fails rather than passing vacuously'
assert_says 'and says so' 'the Capacitor CLI is not installed'

# --- CAP002: a generated file that is not committed --------------------------
new_fixture
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2'
rm "${tmp}/${BUILD}"
run_check
assert_red 'a generated file missing from the tree fails'
assert_says 'and names it' 'CAP002 apps/mobile/android/app/capacitor.build.gradle'

# --- CAP002: no Capacitor project --------------------------------------------
new_fixture
rm -rf "${tmp}/apps/mobile"
run_check
assert_red 'a tree with no Capacitor project fails rather than checking nothing'
assert_says 'and says which directory it wanted' 'CAP002 apps/mobile'

# --- The gitignored trees `cap sync` also writes are not reported -------------
# #299's third criterion. A naive "run it and diff the tree" reports every
# copied asset; only the two files `cap update` owns are compared.
new_fixture
fake_cap <<SH
$(declare -f settings_at)
$(declare -f build_with)
settings_at '8.5.2_@capacitor+core@8.5.2' '8.5.2' > android/capacitor.settings.gradle
build_with 'capacitor-community-bluetooth-le' > android/app/capacitor.build.gradle
mkdir -p android/app/src/main/assets/public android/capacitor-cordova-android-plugins
echo '<!doctype html>' > android/app/src/main/assets/public/index.html
echo 'ext {}' > android/capacitor-cordova-android-plugins/cordova.variables.gradle
SH
run_check
assert_green 'the gitignored trees the generator also writes do not fail the check'
assert_silent_about 'and the copied web build is not reported' 'assets/public'
assert_silent_about 'and neither is the cordova plugin tree' 'capacitor-cordova-android-plugins'

# --- The directory `cap update` writes into is made, and unmade ---------------
# ⚠️ The case CI found and a local run could not. `cap update` writes
# capacitor.plugins.json beside the copied web build, and that directory is
# `cap copy`'s output and gitignored -- so it is present on any machine that has
# ever run `cap sync` and absent from every fresh checkout. This gate's first CI
# run failed with ENOENT while the same command was green locally.
new_fixture
fake_cap <<SH
$(declare -f settings_at)
$(declare -f build_with)
settings_at '8.5.2_@capacitor+core@8.5.2' '8.5.2' > android/capacitor.settings.gradle
build_with 'capacitor-community-bluetooth-le' > android/app/capacitor.build.gradle
echo '[]' > android/app/src/main/assets/capacitor.plugins.json
SH
run_check
assert_green 'a generator writing into the gitignored assets directory works on a fresh checkout'
if [ -e "${tmp}/apps/mobile/android/app/src/main/assets" ]; then
  fail=$((fail + 1))
  printf 'FAIL: the directory the check created was not removed again\n\n'
else
  pass=$((pass + 1))
fi

# --- ...and a directory that was already there is left alone -----------------
new_fixture
mkdir -p "${tmp}/apps/mobile/android/app/src/main/assets/public"
echo 'kept' > "${tmp}/apps/mobile/android/app/src/main/assets/public/index.html"
fake_cap <<SH
$(declare -f settings_at)
$(declare -f build_with)
settings_at '8.5.2_@capacitor+core@8.5.2' '8.5.2' > android/capacitor.settings.gradle
build_with 'capacitor-community-bluetooth-le' > android/app/capacitor.build.gradle
echo '[]' > android/app/src/main/assets/capacitor.plugins.json
SH
run_check
assert_green 'a checkout that already has the assets directory passes too'
if [ "$(cat "${tmp}/apps/mobile/android/app/src/main/assets/public/index.html" 2>/dev/null)" = 'kept' ]; then
  pass=$((pass + 1))
else
  fail=$((fail + 1))
  printf 'FAIL: a directory the check did not create was removed anyway\n\n'
fi

# --- CAP001: the install is verified, and its failure is this check's ---------
# ⚠️ The case that proves --assume-installed is a fixture's flag and not how
# this runs. #298 regenerated from a node_modules nobody had checked against the
# lockfile and committed a *different* wrong path; the install is what stops a
# regenerate-and-diff proving only that two wrong things agree.
new_fixture
generator_writing '8.5.2_@capacitor+core@8.5.2' '8.5.2'
cat > "${tmp}/package.json" <<'JSON'
{ "name": "fixture", "private": true, "dependencies": { "left-pad": "1.3.0" } }
JSON
cat > "${tmp}/pnpm-lock.yaml" <<'YAML'
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:
  .: {}
YAML
run_check_installing
assert_red 'an install that does not match the lockfile fails the check'
assert_says 'and names the rule and the command' 'CAP001 pnpm install --frozen-lockfile'
assert_says 'and quotes what pnpm said, which it writes to stdout' "specifiers in the lockfile don't match"
assert_silent_about 'and regenerates nothing on top of it' 'CAP004'

# --- ...and the same tree passes when the install is taken as given ----------
# The pair that proves the case above is about the install and not about the
# fixture being broken some other way.
run_check
assert_green 'the same tree passes once the install is taken as given'

printf '\n%d passed, %d failed\n' "${pass}" "${fail}"
[ "${fail}" -eq 0 ]
