// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * The realistic bicycle's four maps, drawn from arithmetic — #624.
 *
 * The bicycle under the realistic rider is this repository's own geometry
 * (`src/game/bicycle.ts`), drawn until #624 in three plain materials. What it
 * gains here is SURFACE, not triangles: a tyre's tread and sidewall and the
 * bar's tape as a normal map, the chainring's teeth with the chain on them and
 * the cassette on the rear hub as a normal map and a roughness map, and the
 * frame's clear coat as a roughness map alone. `src/game/bicycle-surfaces.ts`
 * says which part samples where; this file draws what is there.
 *
 * ## Why drawn, and drawn here
 *
 * - **Nothing is downloaded** (ADR 0026 D-4, ADR 0032 D-1), **nothing is
 *   generated by a model**, and **nothing is matched against another
 *   product's pictures** (ADR 0009): every texel is a function of the numbers
 *   below and of the part dimensions `bicycle.ts` already states — the same
 *   posture as `tools/icons/generate-icons.ts`, and dedicated `CC0-1.0` as
 *   those icons are (ADR 0024 D-5).
 * - **Heights in metres, normals from them.** Each band is a height field over
 *   the part's own surface — so many metres along, so many round — and a
 *   texel's normal is the field's slope in METRES per metre, taken at the
 *   part's real size. A 0.6 mm groove is 0.6 mm on the tyre it is drawn for,
 *   and nothing here is a "strength" somebody tuned by eye.
 * - **A pure function of its name.** {@link drawBicycleMap} reads no file, no
 *   clock and no random source; the noise the paint needs is an integer hash
 *   of the lattice point. So `ASSETS.toml`'s `inputsha256` for each map is the
 *   digest of these pixels ({@link pixelDigest}), and `provenance.test.ts`
 *   redraws every map in CI and compares — the decoded-pixel comparison
 *   `tools/icons/generate-icons.test.ts` makes, one step earlier: the pixels
 *   the encoder reads, rather than a PNG whose zlib bytes can drift.
 *
 * The KTX2 files the product loads are these pixels encoded by the pinned
 * `ktx` (`encode-ktx2.ts`), which `process-assets.ts --check` reproduces byte
 * for byte, as it does every other realistic file.
 */

import { createHash } from 'node:crypto';

import { RIDER_BICYCLE_PARTS, RIDER_CRANK_PARTS, type RiderPart } from '../../src/game/bicycle';
import {
  BICYCLE_ATLAS_PIXELS,
  CASSETTE_BAND,
  CHAINRING_BAND,
  CHAINRING_TEETH,
  CHAINRING_TEETH_PER_TILE,
  HUB_RADIUS_METRES,
  HUB_WIDTH_METRES,
  PLAIN_METAL_BAND,
  TAPE_BAND,
  TAPE_WRAP_METRES,
  TAPE_WRAPS_PER_TILE,
  TREAD_PITCH_METRES,
  TREAD_PITCHES_PER_TILE,
  TYRE_BAND,
  type AtlasBand,
} from '../../src/game/bicycle-surfaces';
import type { RealisticBicycleMap } from '../../src/game/realistic-assets';

/** One drawn map: a square of RGB texels, top row first. */
export interface DrawnMap {
  readonly size: number;
  readonly pixels: Uint8Array;
}

/** What each map is, for the KTX2 step: a normal map, or a linear data map. */
export const BICYCLE_MAP_KINDS: Readonly<Record<RealisticBicycleMap, 'normal' | 'data'>> = {
  rubberNormal: 'normal',
  metalNormal: 'normal',
  metalRoughness: 'data',
  paintRoughness: 'data',
};

/** What each map shows, in words — the `modified` its `ASSETS.toml` row opens with. */
export const BICYCLE_MAP_WORDS: Readonly<Record<RealisticBicycleMap, string>> = {
  rubberNormal:
    'a tangent-space normal map drawn from arithmetic: a tyre’s chevron tread ridges across its crown, shoulder, ribbed sidewall and flat bead round its cross-section, and a bar’s overlapping tape round the bar, from height fields in metres at the parts’ own sizes',
  metalNormal:
    'a tangent-space normal map drawn from arithmetic: a chainring’s 48 teeth with the chain’s plates and pins on them, the rear hub with a cassette’s sprockets on its drive side, and plain metal, from height fields in metres at the parts’ own sizes',
  metalRoughness:
    'a roughness map drawn from arithmetic, in step with the metal normal map: polished teeth and sprockets, a duller chain and grease between the sprockets, plain metal at 0.3',
  paintRoughness:
    'a roughness map drawn from arithmetic: a clear coat’s low roughness with a faint mottle, from a periodic value noise over an integer hash, tiling round a tube and along it',
};

/** The side of the paint's roughness map, in texels. It repeats both ways. */
const BICYCLE_PAINT_PIXELS = 128;

/**
 * The cassette's teeth round the hub — one revolution is one tile of its band
 * (`bicycle-surfaces.ts` §`cassetteUv`), so any whole number closes.
 */
const CASSETTE_TEETH = 24;

/* ============================================================================
 * The dimensions — read off `bicycle.ts`, never typed again here
 * ========================================================================== */

function partNamed(parts: readonly RiderPart[], name: string): RiderPart {
  const part = parts.find((each) => each.name === name);
  if (part === undefined) throw new Error(`bicycle.ts has no part called ${name}`);
  return part;
}

function thicknessOf(part: RiderPart): number {
  const solid = part.solid;
  if (solid.shape === 'ring' || solid.shape === 'bend') return solid.thickness;
  if (solid.shape === 'tube') return solid.radius;
  throw new Error(`${part.name} is not round`);
}

/** Round the tyre's cross-section, in metres: `three-renderer.ts` builds it at the ring's thickness. */
const TYRE_SECTION_METRES =
  2 * Math.PI * thicknessOf(partNamed(RIDER_BICYCLE_PARTS, 'front wheel'));
/** Round the bar, in metres. */
const BAR_SECTION_METRES = 2 * Math.PI * thicknessOf(partNamed(RIDER_BICYCLE_PARTS, 'bar tops'));
/** Round the chainring's section: `three-renderer.ts` builds its tube at half its thickness. */
const CHAINRING_SECTION_METRES =
  2 * Math.PI * (thicknessOf(partNamed(RIDER_CRANK_PARTS, 'chainring')) / 2);
/** Round the chainring itself, at its tube's centre. */
const CHAINRING_CIRCUMFERENCE_METRES = (() => {
  const solid = partNamed(RIDER_CRANK_PARTS, 'chainring').solid;
  if (solid.shape !== 'ring') throw new Error('the chainring is not a ring');
  return 2 * Math.PI * solid.radius;
})();

/* ============================================================================
 * Arithmetic
 * ========================================================================== */

const frac = (x: number): number => x - Math.floor(x);

function smoothstep(from: number, to: number, x: number): number {
  const t = Math.min(1, Math.max(0, (x - from) / (to - from)));
  return t * t * (3 - 2 * t);
}

/** A band with soft edges: 1 between `from` and `to`, 0 outside, over `soft` either side. */
function between(x: number, from: number, to: number, soft: number): number {
  return smoothstep(from - soft, from + soft, x) * (1 - smoothstep(to - soft, to + soft, x));
}

/** How far round a closed section a fraction is from its outermost line, in degrees, 0 to 180. */
function offCrown(around: number): number {
  const degrees = frac(around) * 360;
  return degrees > 180 ? 360 - degrees : degrees;
}

/** A height field over a band: `along` a fraction of the tile, `across` a fraction of the band. */
type Height = (along: number, across: number) => number;

/** A band of an atlas, drawn: its height field and what one tile and the band span, in metres. */
interface DrawnBand {
  readonly band: AtlasBand;
  readonly height: Height;
  readonly tileMetres: number;
  readonly acrossMetres: number;
  /** For a roughness map: the roughness at a point, 0 to 1. */
  readonly roughness: Height;
}

/** A texel's fraction across its band: its first row 0, its last 1. @see bicycle-surfaces.ts §bandV */
export function acrossFraction(band: AtlasBand, row: number): number {
  return (row - band.first) / (band.rows - 1);
}

/** A slope to a billionth — far under a byte's step, and the same by any route. */
const snapped = (slope: number): number => Math.round(slope * 1e9) / 1e9;

/** The byte a normal component in −1…1 is stored as. */
const normalByte = (component: number): number => Math.round((component * 0.5 + 0.5) * 255);

/** The byte a roughness in 0…1 is stored as. */
const dataByte = (value: number): number => Math.round(Math.min(1, Math.max(0, value)) * 255);

function drawAtlas(
  bands: readonly DrawnBand[],
  what: 'normal' | 'roughness',
  size: number,
): Uint8Array {
  const pixels = new Uint8Array(size * size * 3);
  for (const drawn of bands) {
    const { band, height } = drawn;
    const stepAlong = 1 / size;
    const stepAcross = 1 / (band.rows - 1);
    for (let row = band.first; row < band.first + band.rows; row += 1) {
      const across = acrossFraction(band, row);
      for (let column = 0; column < size; column += 1) {
        const along = (column + 0.5) / size;
        const at = (row * size + column) * 3;
        if (what === 'roughness') {
          const value = dataByte(drawn.roughness(along, across));
          pixels[at] = value;
          pixels[at + 1] = value;
          pixels[at + 2] = value;
          continue;
        }
        // The slope in metres per metre, by central differences one texel either side.
        const dAlong =
          (height(along + stepAlong, across) - height(along - stepAlong, across)) /
          (2 * stepAlong * drawn.tileMetres);
        const dAcross =
          (height(along, across + stepAcross) - height(along, across - stepAcross)) /
          (2 * stepAcross * drawn.acrossMetres);
        // ⚠️ Snapped to a billionth: a slope of nothing computed a hair
        // either side of zero — the two ends of a closed band reach it by
        // different floating-point routes — would round to 127 at one end
        // and 128 at the other, and the band would not close.
        const alongSlope = snapped(dAlong);
        const acrossSlope = snapped(dAcross);
        const length = Math.hypot(alongSlope, acrossSlope, 1);
        pixels[at] = normalByte(-alongSlope / length);
        pixels[at + 1] = normalByte(-acrossSlope / length);
        pixels[at + 2] = normalByte(1 / length);
      }
    }
  }
  return pixels;
}

/* ============================================================================
 * The rubber: a tyre and the bar tape
 * ========================================================================== */

/**
 * How far a tread ridge stands above the valley beside it, and a sidewall rib
 * and the bead line above the wall.
 *
 * ⚠️ **Rounded ridges, not cut grooves**, and the reason is the mipmaps. A
 * narrow groove is two steep walls of opposite slope a millimetre apart, and a
 * mipmap averages them to flat: at the chase camera a tread period is a few
 * pixels and every groove narrower than one of them had vanished. A ridge
 * that rises and falls over its whole period keeps its slope at every level
 * down to two texels a period, which is what makes the tread read at all.
 */
const TREAD_RIDGE_METRES = 0.0009;
const SIDEWALL_RIB_METRES = 0.00008;
const SIDEWALL_RIDGE_METRES = 0.0004;
/** How far a turn of tape stands proud of the one before it. */
const TAPE_STEP_METRES = 0.0004;
const TAPE_DIMPLE_METRES = 0.00008;

/**
 * The tyre, round its section from the crown: chevron ridges across the crown
 * out to the shoulder, the two arms of each chevron meeting on the centre line;
 * a ribbed sidewall with a raised line round it; and a flat bead where the rim
 * hides it.
 */
const tyreHeight: Height = (along, across) => {
  const off = offCrown(across);
  const tread = 1 - smoothstep(46, 56, off);
  const chevron = TREAD_PITCHES_PER_TILE * along + 0.45 * (off / 50);
  const ridge = TREAD_RIDGE_METRES * (0.5 + 0.5 * Math.cos(2 * Math.PI * chevron)) * tread;
  const sidewall = smoothstep(58, 66, off) * (1 - smoothstep(128, 138, off));
  const ribs = SIDEWALL_RIB_METRES * Math.cos(2 * Math.PI * 32 * along);
  const bead = SIDEWALL_RIDGE_METRES * Math.exp(-(((off - 100) / 4) ** 2));
  return ridge + sidewall * (ribs + bead);
};

/**
 * The bar tape: a helix, each turn a little proud of the last and dropping
 * back where it overlaps, with a grid of shallow perforations along the strip.
 * The helix closes on itself round the bar: one turn round is one turn along.
 */
const tapeHeight: Height = (along, across) => {
  const turn = TAPE_WRAPS_PER_TILE * along - across;
  const strip = frac(turn);
  const step = TAPE_STEP_METRES * strip * (1 - smoothstep(0.9, 0.99, strip));
  const dotAlong = frac(strip * 6) - 0.5;
  const dotRound = frac(across * 16) - 0.5;
  const dimple =
    -TAPE_DIMPLE_METRES * Math.exp(-((dotAlong * dotAlong + dotRound * dotRound) / 0.02));
  return step + dimple;
};

const RUBBER: readonly DrawnBand[] = [
  {
    band: TYRE_BAND,
    height: tyreHeight,
    tileMetres: TREAD_PITCH_METRES * TREAD_PITCHES_PER_TILE,
    acrossMetres: TYRE_SECTION_METRES,
    roughness: () => 1,
  },
  {
    band: TAPE_BAND,
    height: tapeHeight,
    tileMetres: TAPE_WRAP_METRES * TAPE_WRAPS_PER_TILE,
    acrossMetres: BAR_SECTION_METRES,
    roughness: () => 1,
  },
];

/* ============================================================================
 * The metal: the chainring and chain, the cassette, and plain metal
 * ========================================================================== */

/** Plain metal's roughness — the 0.3 the metal material had before #624. */
const PLAIN_METAL_ROUGHNESS = 0.3;
const TOOTH_METRES = 0.0012;
const CHAIN_PLATE_METRES = 0.0007;
const CHAIN_PIN_METRES = 0.0009;
const SPROCKET_METRES = 0.0012;

/** Where the chainring's teeth are round its section, and where the chain sits on them. */
const teethOf = (off: number): number => 1 - smoothstep(38, 52, off);
const chainOf = (off: number): number => smoothstep(44, 54, off) * (1 - smoothstep(100, 110, off));

const chainringHeight: Height = (along, across) => {
  const off = offCrown(across);
  const pitch = CHAINRING_TEETH_PER_TILE * along;
  const link = frac(pitch);
  const tooth = between(link, 0.25, 0.75, 0.1);
  // Alternate links are the outer plates, which stand a little prouder.
  const outer = Math.floor(pitch) % 2 === 0 ? 1 : 0.7;
  const plate = between(link, 0.08, 0.92, 0.05) * outer;
  const fromPin = Math.min(link, 1 - link);
  const pin = Math.exp(-((fromPin / 0.06) ** 2) - ((off - 77) / 9) ** 2);
  return (
    TOOTH_METRES * tooth * teethOf(off) +
    chainOf(off) * (CHAIN_PLATE_METRES * plate) +
    CHAIN_PIN_METRES * pin
  );
};

const chainringRoughness: Height = (_along, across) => {
  const off = offCrown(across);
  return PLAIN_METAL_ROUGHNESS + teethOf(off) * (0.18 - 0.3) + chainOf(off) * (0.55 - 0.3);
};

/** Where across the hub the sprockets are: from just past its middle to its drive-side end. */
const sprocketsOf = (across: number): number => smoothstep(0.52, 0.56, across);
const SPROCKETS = 5;

const cassetteHeight: Height = (along, across) => {
  const stack = ((across - 0.56) / 0.42) * SPROCKETS;
  const index = Math.min(SPROCKETS - 1, Math.max(0, Math.floor(stack)));
  const plate = between(frac(stack), 0.2, 0.7, 0.07);
  const teeth = 0.5 + 0.5 * Math.cos(2 * Math.PI * CASSETTE_TEETH * along);
  // The larger sprockets — nearer the middle of the hub — stand prouder.
  const size = 1 - index / (SPROCKETS * 2);
  return sprocketsOf(across) * plate * SPROCKET_METRES * (size + 0.4 * teeth);
};

const cassetteRoughness: Height = (_along, across) => {
  const stack = ((across - 0.56) / 0.42) * SPROCKETS;
  const plate = between(frac(stack), 0.2, 0.7, 0.07);
  const sprocket = 0.2 * plate + 0.6 * (1 - plate);
  return PLAIN_METAL_ROUGHNESS + sprocketsOf(across) * (sprocket - PLAIN_METAL_ROUGHNESS);
};

const METAL: readonly DrawnBand[] = [
  {
    band: CHAINRING_BAND,
    height: chainringHeight,
    tileMetres: (CHAINRING_CIRCUMFERENCE_METRES * CHAINRING_TEETH_PER_TILE) / CHAINRING_TEETH,
    acrossMetres: CHAINRING_SECTION_METRES,
    roughness: chainringRoughness,
  },
  {
    band: CASSETTE_BAND,
    height: cassetteHeight,
    tileMetres: 2 * Math.PI * HUB_RADIUS_METRES,
    acrossMetres: HUB_WIDTH_METRES,
    roughness: cassetteRoughness,
  },
  {
    band: PLAIN_METAL_BAND,
    height: () => 0,
    tileMetres: 1,
    acrossMetres: 1,
    roughness: () => PLAIN_METAL_ROUGHNESS,
  },
];

/* ============================================================================
 * The paint: a clear coat, as roughness
 * ========================================================================== */

/** An integer hash of a lattice point, 0 to 1 — the whole of the paint's "randomness". */
function latticeValue(i: number, j: number, seed: number): number {
  let h = Math.imul(i, 0x27d4eb2d) ^ Math.imul(j, 0x165667b1) ^ Math.imul(seed, 0x9e3779b1);
  h = Math.imul(h ^ (h >>> 15), 0x85ebca6b);
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
  h ^= h >>> 16;
  return (h >>> 0) / 0x1_0000_0000;
}

/** Value noise, periodic over `cellsX` × `cellsY` cells, at a point in 0…1. */
function periodicNoise(x: number, y: number, cellsX: number, cellsY: number, seed: number): number {
  const gx = x * cellsX;
  const gy = y * cellsY;
  const i = Math.floor(gx);
  const j = Math.floor(gy);
  const tx = smoothstep(0, 1, gx - i);
  const ty = smoothstep(0, 1, gy - j);
  const at = (di: number, dj: number): number =>
    latticeValue(
      (((i + di) % cellsX) + cellsX) % cellsX,
      (((j + dj) % cellsY) + cellsY) % cellsY,
      seed,
    );
  const top = at(0, 0) + (at(1, 0) - at(0, 0)) * tx;
  const bottom = at(0, 1) + (at(1, 1) - at(0, 1)) * tx;
  return top + (bottom - top) * ty;
}

/** A clear coat's roughness, and how far its mottle moves it either way. */
const CLEAR_COAT_ROUGHNESS = 0.2;
const CLEAR_COAT_MOTTLE = 0.05;

function drawPaint(size: number): Uint8Array {
  const pixels = new Uint8Array(size * size * 3);
  for (let row = 0; row < size; row += 1) {
    for (let column = 0; column < size; column += 1) {
      const around = (column + 0.5) / size;
      const along = (row + 0.5) / size;
      const coarse = periodicNoise(around, along, 4, 8, 1) - 0.5;
      const fine = periodicNoise(around, along, 16, 32, 2) - 0.5;
      const value = dataByte(
        CLEAR_COAT_ROUGHNESS + CLEAR_COAT_MOTTLE * (1.4 * coarse + 0.6 * fine),
      );
      const at = (row * size + column) * 3;
      pixels[at] = value;
      pixels[at + 1] = value;
      pixels[at + 2] = value;
    }
  }
  return pixels;
}

/* ============================================================================
 * The four maps
 * ========================================================================== */

/** Draws one of the bicycle's maps. Pure: the same name, the same pixels. */
export function drawBicycleMap(map: RealisticBicycleMap): DrawnMap {
  switch (map) {
    case 'rubberNormal':
      return {
        size: BICYCLE_ATLAS_PIXELS,
        pixels: drawAtlas(RUBBER, 'normal', BICYCLE_ATLAS_PIXELS),
      };
    case 'metalNormal':
      return {
        size: BICYCLE_ATLAS_PIXELS,
        pixels: drawAtlas(METAL, 'normal', BICYCLE_ATLAS_PIXELS),
      };
    case 'metalRoughness':
      return {
        size: BICYCLE_ATLAS_PIXELS,
        pixels: drawAtlas(METAL, 'roughness', BICYCLE_ATLAS_PIXELS),
      };
    case 'paintRoughness':
      return { size: BICYCLE_PAINT_PIXELS, pixels: drawPaint(BICYCLE_PAINT_PIXELS) };
  }
}

/**
 * The digest of a drawn map's pixels: SHA-256 over `<size>x<size>x3\n` and
 * then the texels, top row first. What `ASSETS.toml`'s `inputsha256` records
 * for a drawn map — the picture the encoder read.
 *
 * ⚠️ **These digests rest on V8's `Math.cos`, `Math.exp` and `Math.hypot`**,
 * which ECMAScript leaves implementation-approximated. They reproduce across
 * macOS and Linux on today's pinned Node, which is what makes a digest recorded
 * on one machine checkable on the other. If a Node upgrade moves one of those
 * functions by an ulp and flips a byte, `provenance.test.ts` fails loudly —
 * and the fix is to REDRAW the maps and update the four bicycle rows of
 * `ASSETS.toml` in the same commit, NOT to loosen the test into a tolerance:
 * a digest that tolerates a changed picture records no picture at all.
 */
export function pixelDigest(map: DrawnMap): string {
  return createHash('sha256')
    .update(`${String(map.size)}x${String(map.size)}x3\n`)
    .update(map.pixels)
    .digest('hex');
}
